version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env

  mysql:
    image: mysql:8.4
    restart: always
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "${MYSQL_PUBLISH_PORT}:3306"

volumes:
  mysql_data:
