version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env
    depends_on:
      - mysql
      - redis
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1g

  redis:
    image: redis:7-alpine
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 128m

  mysql:
    image: mysql:8.4
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512m

volumes:
  mysql_data:
