/** Tên biến môi trường — dùng cho ConfigService / process.env, không nhét literal rải rác. */
export const EnvKey = {
  APP_PORT: 'APP_PORT',
  SERVICE_NAME: 'SERVICE_NAME',
  API_BASIC_AUTH_USER: 'API_BASIC_AUTH_USER',
  API_BASIC_AUTH_PASSWORD: 'API_BASIC_AUTH_PASSWORD',
  DOWNLOAD_SHARE_SECRET: 'DOWNLOAD_SHARE_SECRET',
  PUBLIC_APP_URL: 'PUBLIC_APP_URL',
  TELEGRAM_BOT_TOKEN: 'TELEGRAM_BOT_TOKEN',
  TELEGRAM_STORAGE_CHAT_ID: 'TELEGRAM_STORAGE_CHAT_ID',
  /** Chat/channel nhận cảnh báo lỗi (5xx, job queue fail). Để trống = không gửi Telegram. */
  TELEGRAM_ALERT_CHAT_ID: 'TELEGRAM_ALERT_CHAT_ID',
  MAX_UPLOAD_MB: 'MAX_UPLOAD_MB',
  /** Tối đa số file trong một lần tải ZIP cả thư mục (đệ quy). Mặc định trong code nếu không set. */
  FOLDER_ZIP_MAX_FILES: 'FOLDER_ZIP_MAX_FILES',
  UPLOAD_TMP_DIR: 'UPLOAD_TMP_DIR',
  UPLOAD_QUEUE_CONCURRENCY: 'UPLOAD_QUEUE_CONCURRENCY',
  REDIS_HOST: 'REDIS_HOST',
  REDIS_PORT: 'REDIS_PORT',
  REDIS_PASSWORD: 'REDIS_PASSWORD',
  MYSQL_HOST: 'MYSQL_HOST',
  MYSQL_PORT: 'MYSQL_PORT',
  MYSQL_USER: 'MYSQL_USER',
  MYSQL_PASSWORD: 'MYSQL_PASSWORD',
  MYSQL_DATABASE: 'MYSQL_DATABASE',
  MYSQL_ROOT_PASSWORD: 'MYSQL_ROOT_PASSWORD',
  TYPEORM_SYNCHRONIZE: 'TYPEORM_SYNCHRONIZE',
} as const;
